influxdb:
    token: "dozhj19-ML7brHTBiBvxq8PJYNLGqJCoWwCZUDYDIB8RUgEg4Y5uCbQMdPIIO8D6qrfw_k0wcoBn8oB5gDAh0w=="
    org: "home"
    url: "http://192.168.178.27:8086/"

forecast_service:
  # api-endpoint url
  url: "https://www.agrar.basf.de/api/weather/weatherDetails"
  # location: latitude
  latitude: 53.639656
  # location: longitude
  longitude: 9.594956

grid_inverter_service:
  
